CREATE DATABASE BD_ESTOQUE;
GO

USE BD_ESTOQUE;
GO

--TABELA DE CATEGORIAS
CREATE TABLE CATEGORIAS (
	ID_CATEGORIA INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(255)
);

--TABELA FORNECEDORES
CREATE TABLE FORNECEDORES (
	ID_FORNECEDOR INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(150) NOT NULL,
	CONTATO VARCHAR(100),
	TELEFONE VARCHAR(20)
);

--TABELA PRODUTOS
CREATE TABLE PRODUTOS (
	ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(150) NOT NULL,
	ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS(ID_CATEGORIA),
	ID_FORNECEDOR INT FOREIGN KEY REFERENCES FORNECEDORES(ID_FORNECEDOR),
	PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
	QUANTIDADE_ESTOQUE INT DEFAULT 0,
	ESTOQUE_MINIMO INT DEFAULT 5
);

--TABELA DE MOVIMENTAÇÃO (ENTRADA E SAÍDA)
CREATE TABLE MOVIMENTACOES (
	ID_MOVIMENTACAO INT PRIMARY KEY IDENTITY(1,1),
	ID_PRODUTO INT FOREIGN KEY REFERENCES PRODUTOS(ID_PRODUTO),
	TIPO VARCHAR(10) CHECK (TIPO IN ('ENTRADA', 'SAIDA')) NOT NULL,
	QUANTIDADE INT NOT NULL,
	DATA_MOVIMENTACAO DATETIME DEFAULT GETDATE(),
	OBSERVACAO VARCHAR(255)
);

--CATEGORIAS
SELECT * FROM CATEGORIAS;
INSERT INTO CATEGORIAS (NOME, DESCRICAO) VALUES
('Eletrônicos', 'Produtos eletrônicos em geral'),
('Ferramentas', 'Ferramentas manuais e elétricas'),
('Limpeza', 'Produtos de limpeza e higiene'),
('EPI', 'Equipamento de Proteção Individual');

--Fornecedores
SELECT * FROM FORNECEDORES;
INSERT INTO FORNECEDORES (NOME, CONTATO, TELEFONE) VALUES
('Distribuidora Alpha', 'João Silva', '(17) 99999-1111'),
('Fornecedora Beta', 'Maria Souza', '(17) 99999-2222'),
('Comércio Gama', 'Pedro Lima', '(17) 99999-3333');

--Produtos
SELECT * FROM PRODUTOS;
INSERT INTO PRODUTOS (NOME, ID_CATEGORIA, ID_FORNECEDOR, PRECO_UNITARIO, QUANTIDADE_ESTOQUE, ESTOQUE_MINIMO) VALUES
('Cabo USB-C', 1,1,25.90,50,10),
('Furadeira Elétrica', 2,2,189.90,8,3),
('Detergente 500ml', 3,3,4.50,120,20),
('Fone de Ouvido', 1,1,79.90,15,5),
('Chave de Fenda', 2,2,12.00,30,8),
('Desinfetante 1L', 3,3,8.90,60,15),
('Luva de Raspa', 7,2,18.90,2,10),
('Parafuso 3/4', 2,2,0.50,3,15),
('Mangueira 1/2', 3,3,45.00,1,5);

--Movimentação
SELECT * FROM MOVIMENTACOES;
INSERT INTO MOVIMENTACOES (ID_PRODUTO, TIPO, QUANTIDADE, OBSERVACAO) VALUES
(1, 'ENTRADA', 50, 'Compra inicial'),
(2, 'ENTRADA', 10, 'Compra incial'),
(3, 'ENTRADA', 120, 'Compra incial'),
(4, 'ENTRADA', 20, 'Compra inicial'),
(5, 'ENTRADA', 30, 'Compra inicial'),
(6, 'ENTRADA', 60, 'Compra inicial'),
(1, 'SAIDA', 5, 'Venda para cliente'),
(3, 'SAIDA', 15, 'Venda para cliente'),
(4, 'SAIDA', 5, 'Venda para cliente'),
(2, 'SAIDA', 2, 'Venda para cliente');

--Ver todos os produtos com categorias e fornecedor
SELECT 
	P.NOME AS PRODUTO,
	C.NOME AS CATEGORIA,
	F.NOME AS FORNECEDOR,
	P.PRECO_UNITARIO AS PREÇO,
	P.QUANTIDADE_ESTOQUE AS ESTOQUE,
	P.ESTOQUE_MINIMO AS MÍNIMO
FROM PRODUTOS P
INNER JOIN CATEGORIAS C ON P.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FORNECEDORES F ON P.ID_FORNECEDOR = F.ID_FORNECEDOR;

-- Ver produtos com estoque abaixo do mínimo
SELECT NOME, QUANTIDADE_ESTOQUE, ESTOQUE_MINIMO
FROM PRODUTOS
WHERE QUANTIDADE_ESTOQUE <= ESTOQUE_MINIMO;

-- Ver todas as movimentações
SELECT 
	P.NOME AS PRODUTO,
    M.TIPO,
    M.QUANTIDADE,
    M.DATA_MOVIMENTACAO,
    M.OBSERVACAO
FROM MOVIMENTACOES M
INNER JOIN PRODUTOS P ON M.ID_PRODUTO = P.ID_PRODUTO
ORDER BY M.DATA_MOVIMENTACAO DESC;

-- Simula baixa no estoque furadeira
UPDATE PRODUTOS
SET QUANTIDADE_ESTOQUE = 2
WHERE ID_PRODUTO = 2;

-- Passo 1: Deletar movimentações dos produtos duplicados
DELETE FROM MOVIMENTACOES WHERE ID_PRODUTO BETWEEN 7 AND 12;

-- Passo 2: Deletar produtos duplicados
DELETE FROM PRODUTOS WHERE ID_PRODUTO BETWEEN 7 AND 12;

-- Passo 3: Deletar categorias duplicadas
DELETE FROM CATEGORIAS WHERE ID_CATEGORIA BETWEEN 4 AND 6;